-- AlterTable
ALTER TABLE "Member" ADD COLUMN "showPhoneNumber" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Member" ADD COLUMN "showPhoneNumber2" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Member" ADD COLUMN "showEmail2" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Member" ADD COLUMN "showEmail3" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Member" ADD COLUMN "showStudentId" BOOLEAN NOT NULL DEFAULT false;
