-- Add optimistic concurrency version columns
ALTER TABLE "Project" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Event" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "EventCustomField" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "EventRegistration" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ProjectPhase" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
