-- Enable Row-Level Security on all app-owned tables.
-- The backend uses a direct PostgreSQL connection through Prisma,
-- so this blocks direct public Supabase API access without changing
-- the application's existing query path.

ALTER TABLE "Member" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamRole" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subteam" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MemberRoleHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Alumni" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectTeam" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectTag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectPhase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskTeam" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskTag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskDependency" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskActivityLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectActivityLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectScheduleSlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectFile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectFileComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectFolder" ENABLE ROW LEVEL SECURITY;